### ISSUE TITLE
Feature: Resourcen cachen

### ISSUE THREAD

**Issue by timwattenberg** [tanzsport/esv-client-php#5]

**Comment by heneke** [comment]
Die Frage ist, wie man das sinnvoll umsetzt. Die einzelnen Resourcen haben ja ganz unterschiedliche Volatilitäten: Die Gesamtliste der Funktionäre könnte man durchaus für einen ganzen Tag cachen, da sie zur Zeit ohnehin nur einmal pro Tag erzeugt wird. Wenn man z.B. Starter abfragt, dann kommt es ganz darauf an, wann man sie abfragt und was man mit den Daten machen will. Man bräuchte also Caches mit unterschiedlichen Mimiken und Lifetimes.

Außerdem soll die API selbst irgendwann Caching über ETags oder IfModifiedSince ermöglichen. Das könnte man dann direkt Client-Ebene und zusätzlich zu einem eventuellen Application-Level-Cache verwenden.

Kurzum: Ich bin noch unschlüssig.

**Comment by timwattenberg** [comment]
Ich habe mal eine schnelle erste Implementierung gemacht (siehe PR #7) auf die ich mich im weiteren Verlauf beziehe:

> Die Frage ist, wie man das sinnvoll umsetzt. Die einzelnen Resourcen haben ja ganz unterschiedliche Volatilitäten

Möchte man für bestimmte Resourcen die Nutzung eines Caches komplett unterbinden wäre die einfachste Möglichkeit die Cache-Optionen in `Client->boot()` nicht weiter zu geben.

Ansonsten habe ich mir gedacht, dass man in diesem Fall in der eigenen Application zwei `Client`-Instanzen benutzt: Eine mit Cache, die andere ohne.

> Außerdem soll die API selbst irgendwann Caching über ETags oder IfModifiedSince ermöglichen. Das könnte man dann direkt Client-Ebene und zusätzlich zu einem eventuellen Application-Level-Cache verwenden.

(Ich vermute du meinst hier `HttpClient`?) In diesem Fall wäre dies sicherlich sinnvoll, obgleich die Cache-Funktionalität ja dann trotzdem implementiert werden müsste.

**Comment by heneke** [comment]
Integration eines PSR6-Caches auf Applikationsebene folgt.
